### ISSUE TITLE
Migrate away from DigitalOcean to Fly.io

### ISSUE THREAD

**Issue by tupleHunden** [wildcardeve/Discord#6]
Can we just shove this repo at Fly.io and see if it will deploy correctly under a free tier?

**Comment by AgentKD6-37** [comment]
https://fly.io/docs/about/pricing/

Yes. I don't see us passing the free use case and it looks like their pricing model is cheap enough anyway

**Comment by tupleHunden** [comment]
Yup it worked - running in Fly.io on the free tier.
